[package]
name = "virtual-staking-mock"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow          = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-multi-test   = { workspace = true }
cw-storage-plus = { workspace = true }
mesh-bindings   = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
