[package]
name = "mesh-scheduler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
cosmwasm-std     = { workspace = true }
cw-storage-plus  = { workspace = true }