[package]
name = "mesh-price-feed"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
cw-storage-plus  = { workspace = true }
thiserror        = { workspace = true }